name: huluxia_signin
on:
  #push: 进行push的操作时会触发
    #branches: [ master ]
  schedule:    # 定时触发
    - cron: '0 16 * * *'  # 24点
  workflow_dispatch:  # 支持手动触发
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: '初始化python环境'
        uses: actions/setup-python@v4
        with:
           python-version: 3.10.11
      - name: '安装依赖'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: '开始运行'
        id: signin-outputs
        env:
          WECHAT_ROBOT_URL: ${{ secrets.WECHAT_ROBOT_URL }}
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
        run: |
          python ./main.py
